CXX = clang++

10.o: 10.cpp
1.o: 1.cpp
2.o: 2.cpp
3.o: 3.cpp
4.o: 4.cpp
5.o: 5.cpp
6.o: 6.cpp
7.o: 7.cpp
8.o: 8.cpp
9.o: 9.cpp

b1: 1.o
b2: 2.o
b3: 3.o
b4: 4.o
b5: 5.o
b6: 6.o
b7: 7.o
b8: 8.o
b9: 9.o
b10: 10.o

clear: 
	rm *.o *.out